"""generate_tables.py — Frontier Lab Compute Table Generator

Generates the table behind a frontier-lab-compute data explorer: point-in-time
total compute per lab, in H100-equivalents (H100e), with P5 / median / P95
Monte Carlo uncertainty. One row per (lab x end-of-year) snapshot.

This module holds no model structure of its own. It runs the lab Monte Carlos
from ../frontier_lab_compute_model.py (whose priors live in
../lab_model_params.csv) and shapes their sample arrays into the export table.

Usage
-----
    # Save CSVs to data/ and print row counts:
    python generate_tables.py

    # Import and call from another module (e.g. web build):
    from generate_tables import get_all_tables
    tables = get_all_tables()   # dict of {name: DataFrame}

    # Individual getter:
    from generate_tables import get_year_end_by_lab
    df = get_year_end_by_lab()

Tables returned
---------------
    year_end_by_lab      — total H100e (p5 / med / p95) per lab per end-of-year
    intermediates_by_lab — the intermediate quantities behind each lab's final
                           distribution (owned fleets, shares, power, ...), one
                           row per step in model order, with p5 / med / p95

Results are deterministic: each lab model reseeds 42 internally so it
reproduces its canonical notebook run, so there is no seed parameter here.
"""

import datetime
import sys
from pathlib import Path

import numpy as np
import pandas as pd

# The lab models live one directory up (ai-lab-compute/).
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

import frontier_lab_compute_model as flc

DATA_DIR = HERE / "data"

# Row order within a year (the frontier script's presentation order).
LAB_ORDER = ["Google DeepMind", "Meta Superintelligence Labs", "OpenAI", "Anthropic"]

# Each modelled snapshot's key in the frontier module's MODEL_STEPS trace
# registry, in presentation order: lab-major, headline end-2025 before the
# end-2024 backcast. OpenAI's 2023/2024 year-ends fall out of model_openai()
# itself and record no separate trace; Anthropic's end-2024 backcast lives in
# anthropic_2024_backcast and is deliberately not exported here. The 2024
# Meta rows keep the "Meta Superintelligence Labs" label for continuity, but
# cover the predecessor org (Meta AI / GenAI — MSL did not exist in 2024).
LAB_YEAR_KEYS = {
    ("Google DeepMind", 2025): "deepmind",
    ("Google DeepMind", 2024): "deepmind_2024",
    ("Meta Superintelligence Labs", 2025): "msl",
    ("Meta Superintelligence Labs", 2024): "msl_2024",
    ("OpenAI", 2025): "openai",
    ("Anthropic", 2025): "anthropic",
}

COLUMNS = ["Name", "Lab", "Year", "Date",
           "h100e_p5", "h100e_med", "h100e_p95", "Notes"]


# ── Sampling ──────────────────────────────────────────────────────────────────
def run_lab_samples():
    """Run the lab Monte Carlos and return H100e sample arrays keyed by
    (lab, year). OpenAI contributes one snapshot per disclosed year-end
    (2023-2025); DeepMind and Meta get end-2025 plus the end-2024 backcast;
    Anthropic is end-2025 only.

    Per-snapshot percentiles of these arrays are valid, but the models share
    one RNG stream (each reseeds 42), so per-sample values are artificially
    aligned across labs and years — do not sum or ratio samples across rows.
    """
    openai = flc.model_openai()
    samples = {}
    for date, arr in openai["total_h100e_by_date"].items():
        samples[("OpenAI", date.year)] = arr
    samples[("Google DeepMind", 2025)] = flc.model_deepmind()
    samples[("Google DeepMind", 2024)] = flc.model_deepmind_2024()
    samples[("Meta Superintelligence Labs", 2025)] = flc.model_msl()
    samples[("Meta Superintelligence Labs", 2024)] = flc.model_msl_2024()
    samples[("Anthropic", 2025)] = flc.model_anthropic(openai)
    return samples


def run_lab_steps():
    """Run the lab Monte Carlos and return {(lab, year): ordered step list}:
    each snapshot's trace of the intermediate quantities behind its final
    distribution, straight from the frontier module's MODEL_STEPS registry.
    Steps are dicts of name / label / units / kind / expression / samples
    (samples is a scalar for fixed constants)."""
    run_lab_samples()
    return {key: flc.MODEL_STEPS[trace] for key, trace in LAB_YEAR_KEYS.items()}


# ── Table Building ────────────────────────────────────────────────────────────
def build_year_end_table(samples):
    """Shape (lab, year) → samples into the export DataFrame, one row per
    snapshot, sorted by year then by the fixed lab order."""
    notes = f"Generated by lab_compute_tables/generate_tables.py on {datetime.datetime.now():%Y-%m-%d %H:%M}"
    rows = []
    for (lab, year) in sorted(samples, key=lambda k: (k[1], LAB_ORDER.index(k[0]))):
        p5, med, p95 = np.percentile(samples[(lab, year)], [5, 50, 95])
        rows.append({
            "Name": f"{lab} end-{year}",
            "Lab": lab,
            "Year": year,
            "Date": f"{year}-12-31",
            "h100e_p5": p5,
            "h100e_med": med,
            "h100e_p95": p95,
            "Notes": notes,
        })
    return pd.DataFrame(rows, columns=COLUMNS)


INTERMEDIATE_COLUMNS = ["Name", "Lab", "Year", "Step", "Variable", "Label", "Kind",
                        "Units", "Expression", "value_p5", "value_med", "value_p95",
                        "Notes"]


def build_intermediates_table(steps_by_lab_year):
    """Shape the per-snapshot step traces into a tidy DataFrame: one row per
    intermediate quantity, in model order. Percentiles sit under generic
    value_* columns because units vary row to row (see the Units column);
    constants carry the same value in all three."""
    notes = f"Generated by lab_compute_tables/generate_tables.py on {datetime.datetime.now():%Y-%m-%d %H:%M}"
    rows = []
    for (lab, year), steps in steps_by_lab_year.items():
        for order, s in enumerate(steps, start=1):
            samples = s["samples"]
            if np.isscalar(samples):
                p5 = med = p95 = float(samples)
            else:
                p5, med, p95 = np.percentile(samples, [5, 50, 95])
            rows.append({
                "Name": f"{lab} end-{year} · {s['label']}",
                "Lab": lab,
                "Year": year,
                "Step": order,
                "Variable": s["name"],
                "Label": s["label"],
                "Kind": s["kind"],
                "Units": s["units"],
                "Expression": s["expression"],
                "value_p5": p5,
                "value_med": med,
                "value_p95": p95,
                "Notes": notes,
            })
    return pd.DataFrame(rows, columns=INTERMEDIATE_COLUMNS)


# ── Public API ────────────────────────────────────────────────────────────────
def get_all_tables():
    """Run the lab models once and return dict of {table name: DataFrame}."""
    samples = run_lab_samples()
    steps = {key: flc.MODEL_STEPS[trace] for key, trace in LAB_YEAR_KEYS.items()}
    return {
        "year_end_by_lab": build_year_end_table(samples),
        "intermediates_by_lab": build_intermediates_table(steps),
    }


def get_year_end_by_lab():
    return get_all_tables()["year_end_by_lab"]


def get_intermediates_by_lab():
    return get_all_tables()["intermediates_by_lab"]


# ── CLI entry point ───────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("Running frontier lab compute models...")
    tables = get_all_tables()
    DATA_DIR.mkdir(exist_ok=True)
    for name, df in tables.items():
        fname = DATA_DIR / f"lab_compute_{name}.csv"
        df.to_csv(fname, index=False)
        print(f"  {fname.relative_to(HERE)!s:<40} {len(df):>3} rows  {len(df.columns):>2} cols")
    print("Done.")
